### PR TITLE
Add DLK info

### PR DESCRIPTION
**Pull request by dogluck-github**

### CODE REVIEW

**Comment by kasumi-1** [comment]
Hi! Please add liquidity to get added to default list. Thanks.

**Comment by dogluck-github** [comment]
> 你好！请添加流动性以添加到默认列表中。谢谢。

already add liquidity.

**Comment by kasumi-1** [comment]
There is less than $1 ? People need some significant amount so they can trade this.

**Comment by dogluck-github** [comment]
done.
What is the minimum requirement?

**Comment by dogluck-github** [comment]
> There is less than $1 ? People need some significant amount so they can trade this.

done.
What is the minimum requirement?

**Pull request closed without merging**
